#!/bin/bash
#PBS -N get_marker_transcripts_2
#PBS -l walltime=04:00:00
#PBS -l nodes=1:ppn=16
#PBS -l mem=128gb

# Load conda environment
source activate marker_transcripts

# Change directory to where the script was submitted from
cd $PBS_O_WORKDIR

# Run the Python script
#python scripts/get_marker_transcripts.py
#python scripts/get_DIC_marker_transcripts.py
python scripts/get_marker_transcripts_2.py